apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oppgavestyring
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  ingresses:
    - https://aap-oppgavestyring.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
        - application: mottak
        - application: saksbehandling
    outbound:
      external:
        - host: oppgave.dev-fss-pub.nais.io
    rules:
        - application: oppslag
  replicas:
    max: 1
    min: 1
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: oppgavestyring
            envVarPrefix: DB_OPPGAVESTYRING
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
        groups:
          - id: "8bb0ee13-49cd-4e75-8c3d-a13420c8b376"
          - id: "12353679-aa80-4e59-bb47-95e727bfe85c"
          - id: "b60d74dd-fcf7-4c53-a50b-7b20f51804a1"
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
  liveness:
    path: /actuator/live
  readiness:
    path: /actuator/ready
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  secureLogs:
    enabled: true
  env:
      - name: OPPSLAG_URL
        value: "http://oppslag"
      - name: OPPSLAG_SCOPE
        value: api://dev-gcp.aap.oppslag/.default