apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oppgavestyring-proxy
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  accessPolicy:
    inbound:
      rules:
        - application: mottak
    external:
      - host: oppgave.dev-fss-pub.nais.io
  replicas:
    max: 1
    min: 1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
  liveness:
    path: /actuator/live
  readiness:
    path: /actuator/ready
  prometheus:
    enabled: true
    path: /actuator/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  secureLogs:
    enabled: true