kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  truststorePath: ${KAFKA_TRUSTSTORE_PATH}
  keystorePath: ${KAFKA_KEYSTORE_PATH}
  credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}
  clientId: oppgavestyring

database:
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

oauth:
  azure:
    issuer: ${AZURE_OPENID_CONFIG_ISSUER}
    audience: ${AZURE_APP_CLIENT_ID}
    jwksUrl: ${AZURE_OPENID_CONFIG_JWKS_URI}
  roles:
    - ${AAP_SAKSBEHANDLER}
    - ${AAP_BESLUTTER}

axsys:
  url: ${AXSYS_URL}
  scope: ${AXSYS_SCOPE}

azure:
  clientId: ${AZURE_APP_CLIENT_ID}
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  clientSecret: ${AZURE_APP_CLIENT_SECRET}