

CREATE TABLE OPPGAVE (
    ID BIGSERIAL PRIMARY KEY,
    BEHANDLINGSREFERANSE UUID NOT NULL,
    BEHANDLINGSTYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    OPPGAVETYPE VARCHAR(50) NOT NULL,
    GJELDERVERDI VARCHAR(50),
    OPPRETTET TIMESTAMP(3) NOT NULL
);

CREATE TABLE AVKLARINGSBEHOV (
    ID BIGSERIAL PRIMARY KEY,
    OPPGAVE_ID BIGINT REFERENCES OPPGAVE(ID),
    STATUS VARCHAR(50) NOT NULL,
    AVKLARINGSBEHOV VARCHAR(50)
);

CREATE TABLE UTFØRER (
    ID BIGSERIAL PRIMARY KEY,
    ABKLARINGSBEHOV_ID BIGINT REFERENCES AVKLARINGSBEHOV(ID),
    IDENT VARCHAR(50) NOT NULL,
    TIDSSTEMPEL TIMESTAMP(3) NOT NULL
);

CREATE TABLE TILDELT (
    ID BIGSERIAL PRIMARY KEY,
    OPPGAVE_ID BIGINT REFERENCES OPPGAVE(ID),
    IDENT VARCHAR(50) NOT NULL,
    TIDSSTEMPEL TIMESTAMP(3) NOT NULL
);