

CREATE TABLE OPPGAVE_FILTER(
    ID BIGSERIAL PRIMARY KEY,
    TITTEL VARCHAR(50) NOT NULL,
    BESKRIVELSE VARCHAR(255) NOT NULL,
    FILTER_JSON TEXT NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) NOT NULL,
    OPPRETTET_AV VARCHAR(7) NOT NULL
)